BlurCity/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from BlurCity import settings
from Web import Authentication
from Web import Panel
from Web import Home
from Web import Register
from Web.Authentication import urls
from Web.Home import urls
from Web.Panel import urls
from Web.Register import urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'BlurCity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^api/', include(Authentication.urls)),
    url(r'^', include(Home.urls, namespace='Home')),
    url(r'^register/', include(Register.urls, namespace='Register')),
    url(r'^authentication/', include(Authentication.urls, namespace='Authentication')),
    url(r'^panel/', include(Panel.urls, namespace='Panel')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/Authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^choice_login_type', views.choiceLoginTypeView, name='ChoiceLogin'),
    url(r'^login/type=(?P<type>.*)$', views.loginView, name='Login'),
    url(r'^logout_user$', views.logoutUser, name='LogoutUser'),
    url(r'^edit_profile$', views.EditProfileView.as_view(), name='EditProfile'),
]

Web/Home/urls.py
from django.conf.urls import url

from Web.Home import views

urlpatterns = [
    url(r'^$', views.homePageView, name='Home'),
    url(r'^register_admin$', views.registerAdminUser),
    url(r'^how_to_join_us$', views.howToJoinUs, name='how_to_join_us'),
    url(r'^contact', views.contactFunction, name='contact'),

    url(r'administration$', views.adminLogin, name='admin_login'),
    url(r'administration/admin_panel$', views.adminPanel, name='admin_panel'),
    url(r'administration/admin_panel/users_list$', views.validUserList, name='panel_user_list'),
    url(r'administration/admin_panel/new_admin_user$', views.registerAdminUserView, name='panel_new_user'),
    url(r'administration/admin_panel/car_list$', views.validCarList, name='panel_car_list'),
    url(r'administration/admin_panel/send_email$', views.sendEmail, name='panel_send_email'),
    url(r'administration/admin_panel/university_list$', views.universityList, name='panel_university_list'),
    url(r'administration/admin_panel/campus_list$', views.campusList, name='panel_campus_list'),
    url(r'administration/admin_panel/major_list$', views.majorsList, name='panel_major_list'),
    url(r'administration/admin_panel/data$', views.DataView.as_view(), name='panel_data'),

    # WEB SERVICES
    url(r'administration/change_user_status/$', views.changeValidateStatus),
    url(r'administration/change_car_status/$', views.changeCarValidateStatus),
    url(r'administration/get_campus_from_university/$', views.getCampusFromUniversity),
    url(r'administration/get_majors_from_university/$', views.getMajorsFromUniversity),
    url(r'administration/add_university/$', views.addUniversity),
    url(r'administration/add_campus/$', views.addCampus),
    url(r'administration/add_major/$', views.addMajor),

    # DELETE WEB SERVICES
    # USERS
    url(r'administration/delete_user/$', views.deleteUser),

    # UNIVERSITYS
    url(r'administration/delete_university/$', views.deleteUniversity),
    url(r'administration/delete_campus/$', views.deleteCampus),
    url(r'administration/delete_major/$', views.deleteMajor),
]

Web/Panel/urls.py
from django.conf.urls import url

from Web.Panel import views

urlpatterns = [
    url(r'^$', views.panelView, name='Panel'),
    url(r'^car_list/$', views.carListView, name='CarList'),
    url(r'^route_list/$', views.routeListView, name='RouteList'),
    url(r'^route/(?P<route_pk>[0-9]+)/$', views.routeView, name='Route'),
    url(r'^notifications/$', views.notificationView, name='Notifications'),
    url(r'^chat_driver/(?P<user_who_request>[0-9]+)/$', views.messageDriverView, name='MessagesDriver'),
    url(r'^chat_passager/(?P<driver_pk>[0-9]+)/$', views.messagePassagerView, name='MessagesPassager'),

    # WEB SERVICES
    url(r'^save_route/$', views.saveRouteService),
    url(r'^update_route/$', views.updateRouteService),
    url(r'^save_markers/$', views.saveRouteMarkers),
    url(r'^update_markers/$', views.updateRouteMarkers),
    url(r'^make_notification/$', views.makeNotification),
    url(r'^update_notification/$', views.updateNotification),
    url(r'^users_emails/$', views.getUsersEmails),
]

Web/Register/urls.py
from django.conf.urls import url

from Web.Register import views

urlpatterns = [
    url(r'user/$', views.registerUserView, name='RegisterUser'),
    url(r'car/$', views.registerCarView, name='RegisterCar'),
    url(r'route/$', views.registerRoute, name='RegisterRoute'),

    url(r'car=(?P<car_pk>[0-9]+)/update/$', views.editCarView, name='EditCar'),
]

templates/Home/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Zont</title>
    <meta charset="utf-8"/>
    <link rel="icon" href="{% static 'images/favicon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!--[if lte IE 8]><script src="{% static 'home/assets/js/ie/html5shiv.js' %}"></script><![endif]-->
    <link rel="stylesheet" href="{% static 'home/assets/css/main.css' %}"/>
    <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'home/assets/css/ie8.css' %}" /><![endif]-->
</head>
<body class="landing">
<div id="page-wrapper">

    <!-- Header -->
    <header id="header" class="alt">
        <h1><a href="{% url 'Home:Home' %}"><img style="margin-top: 8px" src="{% static 'images/zont_logo_icon.png' %}" /></a></h1>
        <nav id="nav">
            <ul>
                <li><a href="{% url 'Home:Home' %}">Inicio</a></li>
                <li><a href="https://zontmx.wordpress.com/" target="_blank">Blog</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'Authentication:EditProfile' %}">Perfil</a></li>
                    <li><a href="{% url 'Panel:Panel' %}">Panel</a></li>
                    <li><a href="{% url 'Authentication:LogoutUser' %}">Cerrar Sesion</a></li>
                {% else %}
                    <li>
                        <a href="{% url 'Authentication:ChoiceLogin' %}">Iniciar sesi&oacute;n</a>
                    </li>
                    <li><a href="{% url 'Register:RegisterUser' %}" class="button">Registrarse</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <!-- Banner -->
    <section id="banner">
        <h2><img style="height: 200px" src="{% static 'images/zont_logo.png' %}" /></h2>
        <p>Ahorra, viaja r&aacute;pido y c&oacute;modo.</p>
        <ul class="actions">
            <li><a href="{% url 'Register:RegisterUser' %}" class="button special">Registrarse</a></li>
            <li><a id="learn_more" href="#main" class="button">Mas informaci&oacute;n</a></li>
        </ul>
    </section>

    <!-- Main -->
    <section id="main" class="container">

        <section class="box special">
            <header class="major">
                <h2>Si eres de los que piensan que su tiempo vale oro,
                    <br/>
                    toma el control de &eacute;l y viaja con Zont</h2>
                <p></p>
            </header>
            <span class="image featured"><img src="{% static 'images/home_page/car_header.jpg' %}" alt=""/></span>
        </section>

        <div class="row">
            <div class="6u 12u(narrower)">

                <section class="box special">
                    <span class="image featured"><img src="{% static 'images/home_page/car_travel.jpg' %}"
                                                      alt=""/></span>
                    <h3>Viaja sin l&iacute;mites</h3>
                    <p>Encuentra trayectos hacia tu escuela o trabajo y comparte el camino con amigos o
                        compa&ntilde;eros.<br><br>Todo con un par de clicks y toma control de tu movilidad.</p>
                </section>

            </div>
            <div class="6u 12u(narrower)">

                <section class="box special">
                    <span class="image featured"><img src="{% static 'images/home_page/car_driver.jpg' %}"
                                                      alt=""/></span>
                    <h3>¿Qui&eacute;nes conducen?</h3>
                    <p>Personas inteligentes como t&uacute; que trabajan o estudian contigo o muy cerca de ti,
                        conducen y viajan contigo, compartiendo su autom&oacute;vil para reducir sus gastos y los
                        tuyos.</p>
                </section>

            </div>
        </div>

        <section class="box special features">
            <div class="features-row">
                <section>
                    <span class="icon major fa-map-marker accent1"></span>
                    <h3>Rutas</h3>
                    <p>Traza tus rutas hacia la universidad o trabajo y define horarios y d&iacute;as. Comp&aacute;rtelos
                        con tu comunidad y ahorra viajando.</p>
                </section>
                <section>
                    <span class="icon major fa-users accent1"></span>
                    <h3>Comunidad</h3>
                    <p>Encuentra amigos y compa&ntilde;eros con tu mismo destino. Pide un ride y conoce personas como t&uacute;.</p>
                </section>
            </div>
            <div class="features-row">
                <section>
                    <span class="icon major fa-cloud accent1"></span>
                    <h3>Comodidad</h3>
                    <p>Has de tus trayectos una experiencia agradable y c&oacute;moda, mejora tu econom&iacute;a y toma
                        el control de tu tiempo.</p>
                </section>
                <section>
                    <span class="icon major fa-lock accent1"></span>
                    <h3>Seguridad</h3>
                    <p>Los conductores con los que viajas son validados generando un registro para que t&uacute; y todos
                        viajen seguros.</p>
                </section>
            </div>
        </section>

    </section>

    <!-- CTA -->
    <section id="cta">

        <h2>¡Reg&iacute;strate para comenzar a utilizar Zont!</h2>
        <p>Unete a la comunidad que ayuda al planeta al compartir su autom&oacute;vil</p>

        <form>
            <div class="row uniform 50%">
                <div class="12u 12u(mobilep)">
                    <a href="{% url 'Register:RegisterUser' %}" class="button fit">Registrarse</a>
                </div>
            </div>
        </form>
        <form>
            <div class="row uniform 50%">
                <div class="12u 12u(mobilep)">
                    <a href="{% url 'Home:how_to_join_us' %}" class="button fit">Soy instituci&oacute;n y quiero m&aacute;s informaci&oacute;n</a>
                </div>
            </div>
        </form>

    </section>

    <!-- Footer -->
    <footer id="footer">
        <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
        </ul>
        <ul class="copyright">
            <li>&copy; Zont.</li>
            <!--<li>Desarrollado por <a target="_blank" href="http://robertofranco.esy.es">Roberto Franco</a></li>-->
        </ul>
    </footer>

</div>

<!-- Scripts -->
<script src="{% static 'home/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.dropotron.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.scrollgress.min.js' %}"></script>
<script src="{% static 'home/assets/js/skel.min.js' %}"></script>
<script src="{% static 'home/assets/js/util.js' %}"></script>
<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
<script src="{% static 'home/assets/js/main.js' %}"></script>

</body>
</html>