BlurCity/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from BlurCity import settings
from Web import Authentication
from Web import Panel
from Web import Home
from Web import Register
from Web.Authentication import urls
from Web.Home import urls
from Web.Panel import urls
from Web.Register import urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'BlurCity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^api/', include(Authentication.urls)),
    url(r'^', include(Home.urls, namespace='Home')),
    url(r'^register/', include(Register.urls, namespace='Register')),
    url(r'^authentication/', include(Authentication.urls, namespace='Authentication')),
    url(r'^panel/', include(Panel.urls, namespace='Panel')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/Panel/urls.py
from django.conf.urls import url

from Web.Panel import views

urlpatterns = [
    url(r'^$', views.panelView, name='Panel'),
    url(r'^car_list/$', views.carListView, name='CarList'),
    url(r'^route_list/$', views.routeListView, name='RouteList'),
    url(r'^route/(?P<route_pk>[0-9]+)/$', views.routeView, name='Route'),
    url(r'^notifications/$', views.notificationView, name='Notifications'),
    url(r'^chat_driver/(?P<user_who_request>[0-9]+)/$', views.messageDriverView, name='MessagesDriver'),
    url(r'^chat_passager/(?P<driver_pk>[0-9]+)/$', views.messagePassagerView, name='MessagesPassager'),

    # WEB SERVICES
    url(r'^save_route/$', views.saveRouteService),
    url(r'^update_route/$', views.updateRouteService),
    url(r'^save_markers/$', views.saveRouteMarkers),
    url(r'^update_markers/$', views.updateRouteMarkers),
    url(r'^make_notification/$', views.makeNotification),
    url(r'^update_notification/$', views.updateNotification),
    url(r'^users_emails/$', views.getUsersEmails),
]

Core/Notifications/models.py
from django.db import models

# Create your models here.
from Core.Account.models import User


class Notification(models.Model):
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE
    )
    request_user = models.IntegerField()
    status = models.BooleanField()
    route_pk = models.IntegerField()

Web/Panel/models.py
from django.db import models

# Create your models here.

Core/Notifications/views.py
from django.shortcuts import render

# Create your views here.

Web/Panel/views.py
# -*- coding: utf-8 -*-
import json

from datetime import datetime, timedelta
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect
from django.utils import timezone

# Create your views here.
from django.template import RequestContext

from Core.Account.models import User
from Core.Cars.models import Car, CarDocument
from Core.Chat.models import Room, Message
from Core.Notifications.models import Notification
from Core.Routes.models import Route, RouteDay, RouteMarker
from Core.Studies.models import Campus
from Core.baseFunctions import basicArguments, canRequestRoute


def panelView(request):
    args = basicArguments(request)
    try:
        session_type = request.session['session_type']
    except KeyError:
        return redirect('/authentication/choice_login_type')

    if session_type == "driver":
        return render(request, 'Panel/Driver/index.html', args)
    elif session_type == "passenger":
        return render(request, 'Panel/Passenger/index.html', args)


def carListView(request):
    args = basicArguments(request)

    cars = Car.objects.filter(user=request.user)
    cars_documents = []

    for car in cars:
        cars_documents.append(CarDocument.objects.get(car=car))

    args['cars'] = cars
    args['cars_documents'] = cars_documents

    return render(request, 'Panel/Driver/car_list.html', args)


def routeListView(request):
    args = basicArguments(request)

    session_type = request.session['session_type']

    if session_type == "driver":
        routes = Route.objects.filter(user=request.user)

        for route in routes:
            created_at = route.create_at

            # VERIFY THE ROUTE EXPIRE DATE
            if abs(timezone.now() - created_at).days > 6:  # THREE DAYS FOR EXPIRE TIME
                try:
                    Notification.objects.get(route_pk=route.pk, user=route.user).delete()
                except Notification.DoesNotExist:
                    print "Not have notifications"

                # SEND EMAIL NOTIFICATION TO USER
                body = u'Hola %s %s \n\n Te informamos que tu ruta creada en la fecha %s ha expirado, ¡Te invitamos a crear una nueva!' % (
                    route.user.first_name, route.user.last_name, created_at)
                email = EmailMessage(u'Vencimiento de ruta de Blur City', body, to=[route.user.email])
                email.send()

                route.visible = False
                route.save()

        args['routes'] = Route.objects.filter(user=request.user)
        args['session_type'] = session_type
        return render(request, 'Panel/Driver/Routes/route_list.html', args)
    elif session_type == "passenger":
        university = request.user.university
        campus = Campus.objects.filter(university=university)
        pks = []
        for obj_campus in campus:
            pks.append(obj_campus.pk)
        routes = Route.objects.filter(campus_pk__in=pks, visible=True)
        args['routes'] = routes
        args['session_type'] = session_type
        return render(request, 'Panel/Driver/Routes/route_list.html', args)


def routeView(request, route_pk):
    args = basicArguments(request)
    route = Route.objects.get(pk=route_pk)
    cars = Car.objects.filter(user=route.user)
    route_days = RouteDay.objects.filter(route=route)
    route_markers = RouteMarker.objects.filter(route=route)
    campus = Campus.objects.all()

    args['user_cars'] = cars
    args['route'] = route
    args['route_days'] = route_days
    args['route_markers'] = route_markers
    args['campus_list'] = campus
    if request.user == route.user:
        args['is_owner'] = True
        if request.method == "POST":
            print("post")
            return render(request, 'Panel/Driver/Routes/route_view.html', args)
        elif request.method == "GET":
            return render(request, 'Panel/Driver/Routes/route_view.html', args)
    else:
        last_marker = route_markers.last()
        try:
            args['destiny'] = Campus.objects.get(latitude=last_marker.latitude, longitude=last_marker.longitude)
        except:
            args['destiny'] = None
        return render(request, 'Panel/Driver/Routes/route_view.html', args)


def saveRouteService(request):
    origen = request.POST['origen']
    destiny = request.POST['destiny']
    car = request.POST['car']
    sits = request.POST['sits']
    time = request.POST['time']
    days = request.POST.getlist('day[]')

    recovery_amount = request.POST['recovery']

    if recovery_amount == '':
        recovery_amount = 0.0

    route = Route()
    route.user = request.user
    route.campus_pk = destiny
    route.car_pk = car
    route.origin = origen
    route.name = request.user.first_name + "-" + "Ruta"
    route.sits = sits
    route.start_time = time
    route.visible = True
    route.recovery_amount = recovery_amount
    route.save()

    for current_day in days:
        day = RouteDay()
        day.route = route
        day.day = current_day
        day.save()
        print(day.day)

    return HttpResponse(route.pk)


def updateRouteService(request):
    route_pk = request.POST['routePk']
    origen = request.POST['origen']
    destiny = request.POST['destiny']
    car = request.POST['car']
    sits = request.POST['sits']
    time = request.POST['time']
    days = request.POST.getlist('day[]')
    recovery_amount = request.POST['recovery']

    if recovery_amount == '':
        recovery_amount = 0.0

    route = Route.objects.get(pk=route_pk)
    route.campus_pk = destiny
    route.car_pk = car
    route.origin = origen
    route.name = request.user.first_name + "-" + "Ruta"
    route.sits = sits
    route.start_time = time
    route.recovery_amount = recovery_amount
    route.save()
    RouteDay.objects.filter(route=route).delete()

    for current_day in days:
        day = RouteDay()
        day.route = route
        day.day = current_day
        day.save()
    return HttpResponse(route.pk)


def saveRouteMarkers(request):
    markers = json.loads(request.POST['markers_json'])
    for marker in markers:
        route = Route.objects.get(pk=request.POST['routePk'])
        routeMarker = RouteMarker()
        routeMarker.route = route
        routeMarker.position = marker['position']
        routeMarker.latitude = marker['latitud']
        routeMarker.longitude = marker['longitud']
        routeMarker.save()

    return HttpResponse(1)


def updateRouteMarkers(request):
    route = Route.objects.get(pk=request.POST['routePk'])
    RouteMarker.objects.filter(route=route).delete()
    markers = json.loads(request.POST['markers_json'])
    for marker in markers:
        route = Route.objects.get(pk=request.POST['routePk'])
        routeMarker = RouteMarker()
        routeMarker.route = route
        routeMarker.position = marker['position']
        routeMarker.latitude = marker['latitud']
        routeMarker.longitude = marker['longitud']
        routeMarker.save()

    return HttpResponse(1)


def notificationView(request):
    args = basicArguments(request)

    session_type = request.session['session_type']
    args['session_type'] = session_type
    routes = []
    if session_type == "driver":
        notifications = Notification.objects.filter(user=request.user)
        for notification in notifications:
            route = Route.objects.get(pk=notification.route_pk)
            routes.append(route)

        args['notifications'] = notifications
        args['routes'] = routes
        return render(request, 'Panel/notifications.html', args)
    elif session_type == "passenger":
        notifications = Notification.objects.filter(request_user=request.user.pk)

        for notification in notifications:
            route = Route.objects.get(pk=notification.route_pk)
            routes.append(route)

        args['notifications'] = notifications
        args['routes'] = routes
        return render(request, 'Panel/notifications.html', args)


def makeNotification(request):
    route_pk = request.POST['route_pk']
    route_point = request.POST['route_point']
    route = Route.objects.get(pk=route_pk)

    try:
        Notification.objects.get(route_pk=route_pk, request_user=request.user.pk)
        return HttpResponse("2")
    except Notification.DoesNotExist:
        if not canRequestRoute(request.user, route):
            return HttpResponse("3")
        notification = Notification()
        notification.user = route.user
        notification.request_user = request.user.pk
        notification.status = False
        notification.route_pk = route.pk
        notification.save()

        # SEND EMAIL FOR NOTIFY
        body = 'Tienes una nueva solicitud del usuario %s %s \n\n El punto de recogida sugerido por el es el siguiente: %s' % (
            request.user.first_name, request.user.last_name, route_point)
        email = EmailMessage('Nueva solicitud', body, to=[route.user.email])
        email.send()
        return HttpResponse("1")


def updateNotification(request):
    notification = Notification.objects.get(pk=request.POST['notification_pk'])
    request_user = User.objects.get(pk=notification.request_user)
    if request.POST['status'] == "1":
        notification.status = True
        notification.save()
        # SEND EMAIL FOR NOTIFY
        body = u'¡El usuario %s %s ah aceptado tu solicitud de aventon! \n Dirigete a www.blurcity.com para ponerte en contacto con él' % (
            request.user.first_name, request.user.last_name)
        email = EmailMessage(u'Informacion sobre aventon', body, to=[request_user.email])
        email.send()
        return HttpResponse(1)
    else:
        notification.status = False
        notification.save()
        # SEND EMAIL FOR NOTIFY
        body = u'El usuario %s %s ah rechazado tu solicitud de aventón \n Dirígete a www.blurcity.com para buscar un nuevo aventón' % (

templates/Panel/messages.html
{% extends 'Base/base_section.html' %}
{% load static %}

{% block content %}

    <section id="main">
        <div class="row">
            <div class="container">
                <br><br>

                {% if messages %}
                    <div class="row">
                        <div class="container">
                            <div class="col s12">
                                <a class="btn waves-effect waves-light" href="{% url 'Panel:Notifications' %}">
                                    Regresar
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="container">
                            <div class="col s12">
                                {% for message in messages %}
                                    {% if message.user_pk == request.user.pk %}
                                        <div class="chip" style="background: #89cde7; color: white;">
                                            {{ message.message }}
                                        </div>
                                    {% else %}
                                        <div class="chip">
                                            {{ message.message }}
                                        </div>
                                    {% endif %}
                                    <br><br>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% else %}
                    <a class="btn waves-effect waves-light" href="{% url 'Panel:Notifications' %}">
                        Regresar
                    </a>
                    <h5>No se han enviado mensajes aún</h5>
                {% endif %}

                {% if session_type == "driver" %}
                    <div class="row">
                        <div class="container">
                            <div class="col s6">

                            </div>
                            <div class="col s6" align="right">
                                <form action="{% url 'Panel:MessagesDriver' user_who_request %}" method="post">
                                    <input type="hidden" value="{{ request.user.pk }}" name="user_pk">
                                    <div class="input-field col s12">
                                            <textarea name="message" id="message"
                                                      class="materialize-textarea"></textarea>
                                        <label for="message">Mensaje</label>
                                    </div>
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
                                        <i class="material-icons right">send</i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="row">
                        <div class="container">
                            <div class="col s6">

                            </div>
                            <div class="col s6" align="right">
                                <form action="{% url 'Panel:MessagesPassager' driver_pk %}" method="post">
                                    <input type="hidden" value="{{ request.user.pk }}" name="user_pk">
                                    <div class="input-field col s12">
                                        <textarea name="message" id="message" class="materialize-textarea"></textarea>
                                        <label for="message">Mensaje</label>
                                    </div>
                                    <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
                                        <i class="material-icons right">send</i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>
{% endblock %}

templates/Panel/notifications.html
{% extends 'Base/base_app.html' %}
{% load static %}
{% block title %}Solicitudes{% endblock %}
{% block content_main %}
    <div class="row">
        <div class="12u">
            <section class="box">
                <h3>Mis notificaciones</h3>
                <a href="{% url 'Panel:Panel' %}" class="button small">Atr&aacute;s</a>
                <br><br>
                {% if notifications %}
                    <div class="table-wrapper">
                        <table class="alt">
                            <thead>
                            <tr>
                                <th>Nombre de la ruta</th>
                                <th>Estado</th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for notification in notifications %}
                                <tr>
                                    <td>{% for route in routes %}{% if route.pk == notification.route_pk %}
                                        {{ route.name }}
                                    {% endif %}{% endfor %}</td>
                                    <td>{% if notification.status %}
                                        <span id="status" class="green-text">Aceptada</span>{% else %}
                                        <span id="status" class="red-text">No aceptada</span>{% endif %}</td>
                                    {% if session_type == "driver" %}
                                        <td align="center"><a class="button small" style="background: green"
                                                              onclick="updateRequest({{ notification.pk }}, 1)">Aceptar</a>
                                        </td>
                                        <td align="center"><a class="button small" style="background: red"
                                                              onclick="updateRequest({{ notification.pk }}, 0)">Rechazar</a>
                                        </td>
                                    {% endif %}
                                    <td>
                                        <a {% if session_type == "driver" %}href="{% url 'Panel:MessagesDriver' notification.request_user %}"
                                           {% else %}href="{% url 'Panel:MessagesPassager' notification.user.pk %}"{% endif %}>Chat</a>
                                    </td>
                                    <td>
                                        {% for route in routes %}
                                            {% if route.pk == notification.route_pk %}
                                                <a href="{% url 'Panel:Route' route.pk %}">Ver ruta</a>
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3>No se tienen solicitudes</h3>
                {% endif %}

            </section>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {% if session_type == "driver" %}
        <script type="text/javascript">
            function updateRequest(notification_pk, status) {
                $.ajax({
                    url: '/panel/update_notification/',  //Server script to process data
                    type: 'post',
                    success: function (data) {
                        if (data == 1) {
                            document.getElementById("status").innerHTML = "Aceptada";
                            document.getElementById("status").setAttribute("class", "green-text");
                            sweetAlert("Correcto", "La solicitud se ha aceptado correctamente", "success");
                        } else {
                            document.getElementById("status").innerHTML = "Rechazada";
                            document.getElementById("status").setAttribute("class", "red-text");
                            sweetAlert("Correcto", "La solicitud se ha rechazado correctamente", "success");
                        }
                    },
                    error: function (message) {
                        console.log(message);
                    },
                    // Form data
                    data: {
                        'notification_pk': notification_pk,
                        'status': status
                    }
                });
            }
        </script>
    {% endif %}
{% endblock %}