BlurCity/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from BlurCity import settings
from Web import Authentication
from Web import Panel
from Web import Home
from Web import Register
from Web.Authentication import urls
from Web.Home import urls
from Web.Panel import urls
from Web.Register import urls

urlpatterns = [
    # Examples:
    # url(r'^$', 'BlurCity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^api/', include(Authentication.urls)),
    url(r'^', include(Home.urls, namespace='Home')),
    url(r'^register/', include(Register.urls, namespace='Register')),
    url(r'^authentication/', include(Authentication.urls, namespace='Authentication')),
    url(r'^panel/', include(Panel.urls, namespace='Panel')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web/Authentication/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^choice_login_type', views.choiceLoginTypeView, name='ChoiceLogin'),
    url(r'^login/type=(?P<type>.*)$', views.loginView, name='Login'),
    url(r'^logout_user$', views.logoutUser, name='LogoutUser'),
    url(r'^edit_profile$', views.EditProfileView.as_view(), name='EditProfile'),
]

Web/Panel/urls.py
from django.conf.urls import url

from Web.Panel import views

urlpatterns = [
    url(r'^$', views.panelView, name='Panel'),
    url(r'^car_list/$', views.carListView, name='CarList'),
    url(r'^route_list/$', views.routeListView, name='RouteList'),
    url(r'^route/(?P<route_pk>[0-9]+)/$', views.routeView, name='Route'),
    url(r'^notifications/$', views.notificationView, name='Notifications'),
    url(r'^chat_driver/(?P<user_who_request>[0-9]+)/$', views.messageDriverView, name='MessagesDriver'),
    url(r'^chat_passager/(?P<driver_pk>[0-9]+)/$', views.messagePassagerView, name='MessagesPassager'),

    # WEB SERVICES
    url(r'^save_route/$', views.saveRouteService),
    url(r'^update_route/$', views.updateRouteService),
    url(r'^save_markers/$', views.saveRouteMarkers),
    url(r'^update_markers/$', views.updateRouteMarkers),
    url(r'^make_notification/$', views.makeNotification),
    url(r'^update_notification/$', views.updateNotification),
    url(r'^users_emails/$', views.getUsersEmails),
]

Web/Register/urls.py
from django.conf.urls import url

from Web.Register import views

urlpatterns = [
    url(r'user/$', views.registerUserView, name='RegisterUser'),
    url(r'car/$', views.registerCarView, name='RegisterCar'),
    url(r'route/$', views.registerRoute, name='RegisterRoute'),

    url(r'car=(?P<car_pk>[0-9]+)/update/$', views.editCarView, name='EditCar'),
]

Core/Routes/models.py
from django.db import models


# Create your models here.
from Core.Account.models import User


class Route(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    campus_pk = models.IntegerField(default=0)
    car_pk = models.IntegerField(default=0)
    name = models.CharField(max_length=75)
    origin = models.CharField(max_length=75)
    sits = models.IntegerField(default=0)
    start_time = models.TimeField(auto_now=False)
    create_at = models.DateTimeField(auto_now=True)
    recovery_amount = models.FloatField(default=0.0)
    visible = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u"%s" % (self.name)


class RouteDay(models.Model):
    route = models.ForeignKey(
        Route,
        on_delete=models.CASCADE
    )
    day = models.CharField(max_length=75, default='')


class RouteMarker(models.Model):
    route = models.ForeignKey(
        Route,
        on_delete=models.CASCADE
    )
    position = models.IntegerField(default=0)
    latitude = models.CharField(max_length=150, default='')
    longitude = models.CharField(max_length=150, default='')

Core/Studies/models.py
#!/usr/bin/python
# -*- coding: latin-1 -*-

from django.db import models

# Create your models here.
from django.utils.encoding import force_bytes


class University(models.Model):
    name = models.CharField(max_length=75, unique=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u"%s" % (self.name)


class Campus(models.Model):
    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=150, default="0")
    latitude = models.CharField(max_length=150, default='0')
    longitude = models.CharField(max_length=150, default='0')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return u"%s" % (self.name)


class Major(models.Model):
    campus = models.ForeignKey(
        Campus,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=150, default="0")

    def __str__(self):
        return u"%s" % self.name

    def __unicode__(self):
        return u'%s' % self.name

templates/Panel/Driver/Routes/new_route.html
{% extends 'Base/base_app.html' %}
{% load static %}
{% block title %}Nueva ruta{% endblock %}
{% block styles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css"
          rel="stylesheet"/>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"
            type="text/javascript"></script>
{% endblock %}
{% block content_main %}
    <div class="row">
        <div class="12u">

            <!-- Form -->
            <section class="box">
                <h3>Registrar Ruta en Zont</h3>

                {% if user_cars %}
                    <div class="row uniform">
                        <div class="7u 12u(mobilep)">
                            <div id="map"></div>
                            <div class="12u">
                                <br>
                                <ul class="actions">
                                    <li>
                                        <button id="clean-btn" class="button">Borrar marcadores</button>
                                    </li>
                                    <li>
                                        <button id="draw-btn" class="button special">Trazar</button>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="5u 12u(mobilep)">
                            {% if errors %}
                                {% for error in errors %}
                                    <p class="red-text" style="color:red; padding-top: 20px">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            <form method="post" action="{% url 'Authentication:Login' request.session.session_type %}">
                                <div class="row uniform 50%">
                                    <div class="12u 12u(mobilep)">
                                        <div class="select-wrapper">
                                            <select name="origen" id="origen">
                                                <option value="" disabled selected>Seleccione un origen de referencia
                                                </option>
                                                <option value="Centro">Centro</option>
                                                <option value="Plaza">Plaza</option>
                                                <option value="Hogar">Hogar</option>
                                                <option value="Escuela">Escuela</option>
                                                <option value="Trabajo">Trabajo</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="12u 12u(mobilep)">
                                        <div class="select-wrapper">
                                            <select name="destiny" id="destiny">
                                                <option value="0" disabled selected>Seleccione un destino</option>
                                                {% for campus in campus_list %}
                                                    <option value="{{ campus.pk }}">{{ campus.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="12u 12u(mobilep)">
                                        <div class="select-wrapper">
                                            <select name="car" id="car">
                                                <option value="" disabled selected>Seleccione un vehiculo</option>
                                                {% for car in user_cars %}
                                                    <option value="{{ car.pk }}">{{ car.brand }} {{ car.model }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="12u 12u(mobilep)">
                                        <div class="select-wrapper">
                                            <select name="sits" id="sits">
                                                <option value="0" disabled selected>Seleccione un cupo</option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="12u 12u(mobilep)" style="display: -webkit-inline-box;">
                                        <label for="total_sits">Cuota de recuperación($):</label> &nbsp;
                                        <input type="number" min="0" name="recovery" id="recovery"
                                               value="" placeholder="Ejemplo: 30.00"/>
                                    </div>
                                    <div class="12u 12u(mobilep)">
                                        <p style="font-size: 14px; color: #bdbdbd; margin: 0">La cuota de recuperación
                                            es por persona</p>
                                    </div>
                                    <div class="12u 12u(mobilep)">
                                        <p><b>Horario</b></p>
                                        <label for="hora">Hora de inicio</label>
                                        <div class='input-group date' id='datetimepicker3'>
                                            <input id="hora" type='text' name="hora" class="form-control"/>
                                            <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                                        </div>
                                    </div>
                                    <div class="row uniform 50%">
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="lunes" value="Lunes" name="dia[]">
                                            <label for="lunes">Lunes</label>
                                        </div>
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="martes" value="Martes" name="dia[]">
                                            <label for="martes">Martes</label>
                                        </div>
                                    </div>
                                    <div class="row uniform 50%">
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="miercoles" value="Miercoles" name="dia[]">
                                            <label for="miercoles">Miercoles</label>
                                        </div>
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="jueves" value="Jueves" name="dia[]">
                                            <label for="jueves">Jueves</label>
                                        </div>
                                    </div>
                                    <div class="row uniform 50%">
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="viernes" value="Viernes" name="dia[]">
                                            <label for="viernes">Viernes</label>
                                        </div>
                                        <div class="6u 12u(narrower)">
                                            <input type="checkbox" id="sabado" value="Sabado" name="dia[]">
                                            <label for="sabado">S&aacute;bado</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row uniform">
                                    <div class="12u">
                                        <ul class="actions">
                                            <li><a href="{% url 'Panel:Panel' %}" class="button">Cancelar</a></li>
                                            <li><input id="guardar-btn" type="button" class="button special"
                                                       value="Registrar"/></li>
                                        </ul>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% else %}
                    <h4 class="center-align">Por favor registra un automovil primero</h4>
                {% endif %}

                <hr/>

            </section>

        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker3').datetimepicker({
                format: 'LT'
            });
        });
    </script>
    <script type="text/javascript">
        var campus_list = [];
        {% for campus in campus_list %}
            var campus_obj = {
                "pk": {{ campus.pk }},
                "name": "{{ campus.name }}",
                "points": "{{ campus.latitude }},{{ campus.longitude }}",
                "latitude": "{{ campus.latitude }}",
                "longitude": "{{ campus.longitude }}"
            };
            campus_list.push(campus_obj);
        {% endfor %}

    </script>
    <script type="text/javascript" src="{% static 'scripts/maps.js' %}"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=<Token>&callback=initMap">
    </script>
    <script>
        var window_height = $(window).height();
        var main_content_height = $(".main").height();

        if (window_height > main_content_height) {
            var navbar_height = $("#header").height();
            var footer_height = $("#footer").height();

            $("#map").css("height", window_height - navbar_height - footer_height + "px");
        }

        $("#recovery").focusout(function () {
            var total_sits = $("#recovery").val();

            if (total_sits < 0) {
                $("#recovery").val(0);
                sweetAlert("Error", "Solo puedes colocar un valor positivo", "error");
            }
        });

        //DESTINY MARKER SECTION

        var destiny_helper_marker = null;

        $('#destiny').change(function () {
            var campus_pk = $('#destiny').val();
            switch (campus_pk) {
                {% for campus in campus_list %}
                    case '{{ campus.pk }}':
                        for (var i = 0; i < campus_list.length; i++) {
                            if (campus_list[i].pk == {{ campus.pk }}) {
                                latLng = new google.maps.LatLng({
                                    lat: Number(campus_list[i].latitude),
                                    lng: Number(campus_list[i].longitude)
                                });
                                if (destiny_helper_marker != null) {
                                    destiny_helper_marker.setMap(null);
                                }
                                destiny_helper_marker = new google.maps.Marker({
                                    position: latLng,
                                    map: map,
                                    label: {
                                        color: 'black',
                                        fontWeight: 'bold',
                                        text: 'Destino'
                                    },
                                    icon: {
                                        url: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                                        labelOrigin: new google.maps.Point(11, 40)
                                    }
                                });
                                map.setCenter(latLng);
                            }
                        }
                        break;
                {% endfor %}
                default:
                    break;
            }
        });

    </script>

{% endblock %}

templates/Panel/Driver/Routes/route_list.html
{% extends 'Base/base_app.html' %}
{% load static %}
{% block title %}Lista de rutas{% endblock %}
{% block content_main %}
    <div class="row">
        <div class="12u">
            <section class="box">
                <h3>Mis rutas</h3>
                <a href="{% url 'Panel:Panel' %}" class="button small">Atr&aacute;s</a>
                <br><br>
                {% if routes %}
                    <div class="table-wrapper">
                        <table class="alt">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Origen de referencia</th>
                                <th>Hora de inicio</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for route in routes %}
                                <tr>
                                    <td>{{ route.name }}</td>
                                    <td>{{ route.origin }}</td>
                                    <td>{{ route.start_time }}</td>
                                    <td><a href="{% url 'Panel:Route' route.pk %}">
                                        {% if session_type == 'driver' %}
                                            <i class="fa fa-pencil"
                                               aria-hidden="true"></i>
                                        {% else %}
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        {% endif %}
                                    </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% elif session_type == 'driver' %}
                    <h3>No tienes rutas creadas, <a href="{% url 'Register:RegisterRoute' %}">¡Crea una!</a></h3>
                {% else %}
                    <h3>No se tienen rutas creadas en la plataforma.</h3>
                {% endif %}
            </section>
        </div>
    </div>
{% endblock %}